- name: Delete all docker containers
  become: yes
  shell: "docker rm -f $(docker ps -aq)"
  ignore_errors: yes
  tags:
    - clean
    - clean_containers
    - upgrade


- name: Delete all docker images
  become: yes
  shell: "docker rmi -f $(docker images -q)"
  ignore_errors: yes
  tags:
    - clean
    - clean_images
