- name: Set up osf
  hosts: all
  pre_tasks:
    - fail: msg="One or more tags must be specified to run this playbook"
  vars:
    docker_storage: no
    docker_storage_name: "{{ docker_env }}_osf_storage_1"
    docker_storage_dir: "/opt/{{ docker_env }}_osf_storage/"
    docker_storage_conf_dir: "{{ docker_storage_dir }}conf/"
    docker_storage_copy_ops:
      - src: roles/docker-osf/files/conf/
        dest: "{{ docker_storage_conf_dir }}"
    docker_storage_file_ops:
      - state: directory
        path: "{{ docker_storage_dir }}code/"
    docker_storage_volumes:
      - "{{ docker_storage_conf_dir }}code/:/code:rw"
      - "{{ docker_storage_conf_dir }}api/local.py:/code/api/base/settings/local.py:ro"
      - "{{ docker_storage_conf_dir }}website/local.py:/code/website/settings/local.py:ro"

    docker_elasticsearch: no
    docker_elasticsearch_name: "{{ docker_env }}_osf_elasticsearch_1"
    docker_elasticsearch_conf_dir: "/opt/{{ docker_env }}_osf_elasticsearch/conf/"
    docker_elasticsearch_data_dir: "/opt/{{ docker_env }}_osf_elasticsearch/data/"

    docker_tokumx: no
    docker_tokumx_name: "{{ docker_env }}_osf_tokumx_1"
    docker_tokumx_conf_dir: "/opt/{{ docker_env }}_osf_tokumx/conf/"
    docker_tokumx_data_dir: "/opt/{{ docker_env }}_osf_tokumx/data/"

    # postgres
    docker_postgres: no
    docker_postgres_conf_dir: "/opt/{{ docker_env }}_osf_postgres/conf/"
    docker_postgres_data_dir: "/opt/{{ docker_env }}_osf_postgres/data/"
    docker_postgres_name: "{{ docker_env }}_osf_postgres_1"
    docker_postgres_env:
      POSTGRES_DB: "osf_admin_{{ docker_env }}"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    docker_rabbitmq: no
    docker_rabbitmq_name: "{{ docker_env }}_osf_rabbitmq_1"
    docker_rabbitmq_data_dir: "/opt/{{ docker_env }}_osf_rabbitmq/data/"

    docker_celery_flower: no
    docker_celery_flower_name: "{{ docker_env }}_osf_celery_flower_1"
    docker_celery_flower_command: "flower --broker=amqp://guest:guest@rabbitmq:5672//"
    docker_celery_flower_links:
      - "{{ docker_rabbitmq_name }}:rabbitmq"

    # redis
    docker_redis_name: "{{ docker_env }}_osf_prerender_redis_1"
    docker_redis_data_dir: "/opt/{{ docker_env }}_osf_prerender_redis/data/"

    docker_prerender: no
    docker_prerender_name: "{{ docker_env }}_osf_prerender_1"
    docker_prerender_conf_dir: "/opt/{{ docker_env }}_osf_prerender/conf/"
    docker_sentry_server_links:
      - "{{ docker_redis_name }}:redis"

    docker_osf_adminserver_name: "{{ docker_env }}_osf_adminserver_1"
    docker_osf_adminserver_conf_dir: "/opt/{{ docker_env }}_osf_adminserver/conf/"
    docker_osf_adminserver_data_dir: "/opt/{{ docker_env }}_osf_adminserver/data/"
    docker_osf_adminserver_links:
      - "{{ docker_elasticsearch_name }}:elasticsearch"
      - "{{ docker_tokumx_name }}:tokumx"
      - "{{ docker_rabbitmq_name }}:rabbitmq"
    docker_osf_adminserver_volumes_from:
      - "{{ docker_storage_name }}"

    docker_preprints: no
    docker_preprints_source_branch: develop
    docker_preprints_source_repo: https://github.com/CenterForOpenScience/ember-preprints.git
    docker_preprints_working_dir: /preprints/
    docker_preprints_name: "{{ docker_env }}_preprints_1"
    docker_preprints_image: centerforopenscience/ember:latest
    docker_preprints_command: gosu www-data ember build --env production --output-path=/preprints/dist/preprints
    docker_preprints_source_conf_dir: roles/docker-spa/files/preprints/
    docker_preprints_code_dir: "/opt/{{ docker_env }}_preprints/code/"
    docker_preprints_conf_dir: "/opt/{{ docker_env }}_preprints/conf/"
    docker_preprints_env:
      SOURCE_BRANCH: "{{ docker_preprints_source_branch }}"
      SOURCE_REPO: "{{ docker_preprints_source_repo }}"
      WORKDIR: "{{ docker_preprints_working_dir }}"
      BACKEND: "{{ docker_preprints_backend }}"
    docker_preprints_net: bridge
    docker_preprints_hostname: "{{ hostname_name }}"
    docker_preprints_links: []
    docker_preprints_volumes:
      - "{{ docker_preprints_code_dir }}:{{ docker_preprints_working_dir }}:rw"
      - "{{ docker_preprints_conf_dir }}env:{{ docker_preprints_working_dir }}.env:rw"
    docker_preprints_volumes_from: []
 
    docker_osf_apiserver_name: "{{ docker_env }}_osf_apiserver_1"
    docker_osf_apiserver_conf_dir: "/opt/{{ docker_env }}_osf_apiserver/conf/"
    docker_osf_apiserver_links:
      - "{{ docker_elasticsearch_name }}:elasticsearch"
      - "{{ docker_tokumx_name }}:tokumx"
      - "{{ docker_rabbitmq_name }}:rabbitmq"
    docker_osf_apiserver_volumes_from:
      - "{{ docker_storage_name }}"

    docker_osf_server_name: "{{ docker_env }}_osf_server_1"
    docker_osf_server_conf_dir: "/opt/{{ docker_env }}_osf_server/conf/"
    docker_osf_server_links:
      - "{{ docker_elasticsearch_name }}:elasticsearch"
      - "{{ docker_tokumx_name }}:tokumx"
      - "{{ docker_rabbitmq_name }}:rabbitmq"
    docker_osf_server_volumes_from:
      - "{{ docker_storage_name }}"
      - "{{ docker_preprints_name }}"
 
    docker_osf_celery_beat_name: "{{ docker_env }}_osf_celery_beat"
    docker_osf_celery_beat_data_dir: "/opt/{{ docker_env }}_osf_celery_beat/data/"
    docker_osf_celery_beat_log_dir: "/opt/{{ docker_env }}_osf_celery_beat/log/"
    docker_osf_celery_beat_links:
      - "{{ docker_rabbitmq_name }}:rabbitmq"
      - "{{ docker_elasticsearch_name }}:elasticsearch"
      - "{{ docker_tokumx_name }}:tokumx"
    docker_osf_celery_beat_volumes_from:
      - "{{ docker_storage_name }}"

    docker_osf_celery_worker_name: "{{ docker_env }}_osf_celery_worker"
    docker_osf_celery_worker_data_dir: "/opt/{{ docker_env }}_osf_celery_worker/data/"
    docker_osf_celery_worker_log_dir: "/opt/{{ docker_env }}_osf_celery_worker/log/"
    docker_osf_celery_worker_links:
      - "{{ docker_rabbitmq_name }}:rabbitmq"
      - "{{ docker_elasticsearch_name }}:elasticsearch"
      - "{{ docker_tokumx_name }}:tokumx"
    docker_osf_celery_worker_volumes_from:
      - "{{ docker_storage_name }}"

    docker_osf_cron_name: "{{ docker_env }}_osf_cron"
    docker_osf_cron_links:
      - "{{ docker_rabbitmq_name }}:rabbitmq"
      - "{{ docker_elasticsearch_name }}:elasticsearch"
      - "{{ docker_tokumx_name }}:tokumx"
    docker_osf_cron_volumes_from:
      - "{{ docker_storage_name }}"

    docker_osf_sharejs_name: "{{ docker_env }}_osf_sharejs_1"
    docker_osf_sharejs_command: "invoke sharejs"
    docker_osf_sharejs_conf_db_name: sharejs
    docker_osf_sharejs_conf_db_url: mongodb://tokumx:27017/sharejs
    docker_osf_sharejs_links:
      - "{{ docker_tokumx_name }}:tokumx"
    docker_osf_sharejs_volumes_from:
      - "{{ docker_storage_name }}"

    docker_nginx: no
    docker_nginx_name: "{{ docker_env }}_osf_nginx_1"
    docker_nginx_image: centerforopenscience/nginx:1 # auto reload on /etc/hosts change
    docker_nginx_source_conf_dir: roles/docker-osf/files/nginx/
    docker_nginx_conf_dir: "/opt/{{ docker_env }}_osf_nginx/conf/"
    docker_nginx_expose:
      - 80
      - 443
      - 3000
    docker_nginx_links:
      - "{{ docker_osf_adminserver_name }}:adminserver"
      - "{{ docker_osf_apiserver_name }}:apiserver"
      - "{{ docker_osf_server_name }}:server"
      - "{{ docker_osf_sharejs_name }}:sharejs"
      - "{{ docker_prerender_name }}:prerender"
      - "{{ docker_preprints_name }}:preprints"
    docker_nginx_volumes_from:
      - "{{ docker_storage_name }}"
      - "{{ docker_preprints_name }}"
  roles:
    - role: docker-storage
      when: docker_storage

    - role: docker-elasticsearch
      when: docker_elasticsearch

    - role: docker-tokumx
      when: docker_tokumx

    - role: docker-postgres
      when: docker_postgres

    - role: docker-redis
      when: docker_redis

    - role: docker-rabbitmq
      when: docker_rabbitmq

    - role: docker-celery-flower
      when: docker_celery_flower

    - role: docker-prerender
      when: docker_prerender

    - role: docker-ember
      docker_ember_source_branch: "{{ docker_preprints_source_branch }}"
      docker_ember_source_repo: "{{ docker_preprints_source_repo }}"
      docker_ember_working_dir: "{{ docker_preprints_working_dir }}"
      docker_ember_name: "{{ docker_preprints_name }}"
      docker_ember_image: "{{ docker_preprints_image }}"
      docker_ember_command: "{{ docker_preprints_command }}"
      docker_ember_source_conf_dir: "{{ docker_preprints_source_conf_dir }}"
      docker_ember_code_dir: "{{ docker_preprints_code_dir }}"
      docker_ember_conf_dir: "{{ docker_preprints_conf_dir }}"
      docker_ember_env: "{{ docker_preprints_env }}"
      docker_ember_net: "{{ docker_preprints_net }}"
      docker_ember_hostname: "{{ docker_preprints_hostname }}"
      docker_ember_links: "{{ docker_preprints_links }}"
      docker_ember_volumes: "{{ docker_preprints_volumes }}"
      docker_ember_volumes_from: "{{ docker_preprints_volumes_from }}"
      when: docker_preprints

    - role: docker-osf

    - role: docker-nginx
      when: docker_nginx
