# variables
docker_dor_source_branch: master
docker_dor_source_repo: https://github.com/CenterForOpenScience/DirectoryOfRepositories.git

# server
docker_dor_server: no
docker_dor_server_name: dor_server_1
docker_dor_server_image: centerforopenscience/dor:laster
docker_dor_server_command: "uwsgi --ini /etc/uwsgi/uwsgi.ini"
docker_dor_server_source_conf_file: uwsgi.ini
docker_dor_server_conf_dir: /opt/dor_server/conf/
docker_dor_server_conf_file: "{{ docker_dor_server_conf_dir }}uwsgi.ini"
docker_dor_server_env:
  SOURCE_BRANCH: "{{ docker_dor_source_branch }}"
  SOURCE_REPO: "{{ docker_dor_source_repo }}"
docker_dor_server_net: bridge
docker_dor_server_hostname: "{{ hostname_name }}"
docker_dor_server_expose:
  - 8000
docker_dor_server_ports: []
docker_dor_server_links: []
docker_dor_server_volumes:
  - "{{ docker_dor_server_conf_file }}:/etc/uwsgi/uwsgi.ini"
  - "{{ docker_storage_conf_dir }}local.py:/code/RepoDir/settings/local.py:ro"
docker_dor_server_volumes_from: []
