# file: roles/apt/tasks/main.yml


- name: Apt | Update the sources list (/etc/apt/sources.list)
  copy: src=etc_apt_sources.list dest=/etc/apt/sources.list owner=root group=root mode=0644

- name: Apt | Update APT package cache
  apt: update_cache=yes
  sudo: yes

- name: Apt | Run apt-get upgrade
  apt: upgrade=full
  sudo: yes

- name: Apt | Check for vagrant
  shell: ls -ld .vbox_version | awk '{print $3}'
  register: is_vagrant

# https://github.com/pjan/the-ansibles/blob/master/roles/apt/tasks/main.yml

- name: Apt | Prepare vagrant (reboot machine, login, and run vboxadd setup)
  shell: /etc/init.d/vboxadd setup
  sudo: yes
  when: is_vagrant.stdout == 'vagrant'
