- name: Set vm.swappiness in /etc/sysctl.conf
  sysctl:
    name: vm.swappiness
    value: "{{ swap_vm_swappiness }}"
    state: present
  tags:
    - install


- name: Set vm.vfs_cache_pressure in /etc/sysctl.conf
  sysctl:
    name: vm.vfs_cache_pressure
    value: "{{ swap_vm_vfs_cache_pressure }}"
    state: present
  tags:
    - install


- name: Create the file to be used for swap
  become: yes
  shell: fallocate -l {{ swap_swapfile_size }} /swapfile
  tags:
    - install


- name: Secure swap file permissions
  become: yes
  shell: chmod 600 /swapfile
  tags:
    - install


- name: Format the swapfile
  become: yes
  shell: mkswap /swapfile
  tags:
    - install


- name: Add the file to the system as a swap file
  become: yes
  shell: swapon /swapfile
  tags:
    - install


- name: Add the the swap file to /etc/fstab
  mount:
    src: /swapfile
    name: none
    fstype: swap
    opts: sw
    state: present
  tags:
    - install
