csf_csfpre_file: ""
csf_csfpost_file: ""

csf_auto_update: 0
csf_faststart: 0

csf_testing: 0
csf_testing_interval: 5
# 22 is required for inbound SSH
csf_tcp_in: "22"
csf_tcp6_in: "22"

# 80 is required for outbound HTTP (e.g., apt)
# 443 is required for outbound SSL (e.g., pip)
csf_tcp_out: "80,443"
csf_tcp6_out: "80,443"

csf_udp_in: ""
csf_udp_out: ""
csf_udp6_in: ""
csf_udp6_out: ""

# Email where to send lfd alerts
csf_lf_alert_to: ""
# From: field setting for lfd email alerts
csf_lf_alert_from: ""

csf_ui: 1
csf_ui_allow: 1
csf_ui_user: ""
csf_ui_password: ""

# Restrict ability to modify csf config from the csf UI
# 0 = Unrestricted UI
# 1 = Restricted UI
# 2 = Disabled UI
csf_restrict_ui: 2

# Allow ping requests
csf_icmp_in: 1

# Filter invalid, unwanted, and illegal packets
csf_packet_filter: 1

# Synflood protection. Slows initialization of all connections, so
# ONLY enable if you know you are under attack
csf_synflood: 0
csf_synflood_rate: "100/s"
csf_synflood_burst: 150


# limit number of concurrent active connections on port
# Example:
# 22;5;443;20
# allows 5 concurrent connections on port 22 and 20 concurrent connections on port 443
csf_connlimit: ""


# Limit number of connections per time interval that can be made to specific
# ports.
# Example:
# 22;tcp;5;250
# would block the IP address i more than 5 connections are established on port 22 using
# TCP within 250 seconds
csf_portflood: ""

# Login failure detection (LFD)
# #############################

# Number of sshd login failures before banning the IP
csf_lf_sshd: 5
# 1 to block permanently, or a number of seconds to block the IP
csf_lf_sshd_perm: 1

# Send an email alert if anyone logs in successfully using SSH
csf_ssh_email_alert: 1

# Send an email alert if anyone uses su to access another account. This will
# send an email alert whether the attempt to use su was successful or not
csf_lf_su_email_alert: 1


csf_ui_allowed_ips:

csf_ct_limit: "0"
csf_ct_ports: ""