- name: Restart docker postgres container
  become: yes
  shell: "docker restart {{ docker_postgres_name }}"
  tags:
    - restart


- name: Ensure docker postgres directories exist
  become: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_postgres_data_dir }}"
  tags:
    - install
    - upgrade


- name: Run docker postgres container
  docker:
    env: "{{ docker_postgres_env }}"
    expose: "{{ docker_postgres_expose }}"
    hostname: "{{ docker_postgres_hostname }}"
    image: "{{ docker_postgres_image }}"
    links: "{{ docker_postgres_links }}"
    name: "{{ docker_postgres_name }}"
    net: "{{ docker_postgres_net }}"
    ports: "{{ docker_postgres_ports }}"
    pull: always
    restart_policy: always
    state: reloaded
    volumes: "{{ docker_postgres_volumes }}"
  tags:
    - install
    - upgrade
