- name: Restart docker waterbutler celery container
  become: yes
  shell: "docker restart {{ docker_waterbutler_celery_name }}_{{ item }}"
  with_sequence: count={{ docker_waterbutler_celery_instances }}
  when: docker_waterbutler_celery_instances > 0
  tags:
    - restart


- name: Run docker waterbutler celery container
  docker:
    command: "{{ docker_waterbutler_celery_command }}"
    env: "{{ docker_waterbutler_celery_env }}"
    expose: "{{ docker_waterbutler_celery_expose }}"
    hostname: "{{ docker_waterbutler_celery_hostname }}"
    image: "{{ docker_waterbutler_celery_image }}"
    links: "{{ docker_waterbutler_celery_links }}"
    name: "{{ docker_waterbutler_celery_name }}_{{ item }}"
    net: "{{ docker_waterbutler_celery_net }}"
    ports: "{{ docker_waterbutler_celery_ports }}"
    pull: always
    restart_policy: always
    state: reloaded
    tty: yes
    volumes: "{{ docker_waterbutler_celery_volumes }}"
    volumes_from: "{{ docker_waterbutler_celery_volumes_from }}"
  with_sequence: count={{ docker_waterbutler_celery_instances }}
  when: docker_waterbutler_celery_instances > 0
  tags:
    - install
    - upgrade
