- name: Restart docker cassandra container
  become: yes
  shell: "docker restart {{ docker_cassandra_name }}"
  tags:
    - restart


- name: Ensure docker cassandra directories exist
  become: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_cassandra_data_dir }}"
  tags:
    - install
    - upgrade


- name: Run docker cassandra container
  docker:
    env: "{{ docker_cassandra_env }}"
    expose: "{{ docker_cassandra_expose }}"
    hostname: "{{ docker_cassandra_hostname }}"
    image: "{{ docker_cassandra_image }}"
    name: "{{ docker_cassandra_name }}"
    ports: "{{ docker_cassandra_ports }}"
    pull: always
    restart_policy: always
    state: reloaded
    volumes: "{{ docker_cassandra_volumes }}"
    volumes_from: "{{ docker_cassandra_volumes_from }}"
  tags:
    - install
    - upgrade
