- name: Ensure docker nginx directories exist
  become: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_nginx_conf_dir }}"
    - "{{ docker_nginx_confd_dir }}"
    - "{{ docker_nginx_ssl_dir }}"
  tags:
    - install
    - nginx-install
    - settings
    - nginx-settings


- name: Copy docker nginx nginx.conf file
  copy:
    src: "{{ docker_nginx_source_nginx_conf_file }}"
    dest: "{{ docker_nginx_nginx_conf_file }}"
    mode: 0644
  when: docker_nginx_source_nginx_conf_file | default("") != ""
  tags:
    - install
    - nginx-install
    - settings
    - nginx-settings


- name: Copy docker nginx .htpasswd file
  copy:
    src: "{{ docker_nginx_source_htpasswd_file }}"
    dest: "{{ docker_nginx_htpasswd_file }}"
    mode: 0644
  when: docker_nginx_source_htpasswd_file | default("") != ""
  tags:
    - install
    - nginx-install
    - settings
    - nginx-settings


- name: Clear docker nginx conf.d directory
  shell: "rm -Rf {{ docker_nginx_confd_dir }}*"
  when: docker_nginx_source_confd_dir | default("") != ""
  tags:
    - install
    - nginx-install
    - settings
    - nginx-settings


- name: Copy docker nginx conf.d directory
  copy:
    mode: 0644
    src: "{{ docker_nginx_source_confd_dir }}"
    dest: "{{ docker_nginx_confd_dir }}"
  when: docker_nginx_source_confd_dir | default("") != ""
  tags:
    - install
    - nginx-install
    - settings
    - nginx-settings


- name: Clear docker nginx ssl certificates
  shell: "rm -Rf {{ docker_nginx_ssl_dir }}*"
  when: docker_nginx_source_ssl_dir | default("") != ""
  tags:
    - install
    - nginx-install
    - settings
    - nginx-settings


- name: Copy docker nginx ssl certificates
  copy:
    mode: 0600
    src: "{{ docker_nginx_source_ssl_dir }}"
    dest: "{{ docker_nginx_ssl_dir }}"
  when: docker_nginx_source_ssl_dir | default("") != ""
  tags:
    - install
    - nginx-install
    - settings
    - nginx-settings


- name: Restart docker nginx container
  become: yes
  shell: "docker restart {{ docker_nginx_name }}"
  tags:
    - restart
    - nginx-restart


- name: Run docker nginx container
  docker:
    env: "{{ docker_nginx_env }}"
    expose: "{{ docker_nginx_expose }}"
    hostname: "{{ docker_nginx_hostname }}"
    image: "{{ docker_nginx_image }}"
    links: "{{ docker_nginx_links }}"
    name: "{{ docker_nginx_name }}"
    net: "{{ docker_nginx_net }}"
    ports: "{{ docker_nginx_ports }}"
    pull: always
    restart_policy: always
    state: reloaded
    volumes: "{{ docker_nginx_volumes }}"
    volumes_from: "{{ docker_nginx_volumes_from }}"
  tags:
    - install
    - nginx-install
