# variables
docker_osf_source_branch: master
docker_osf_source_repo: https://github.com/CenterForOpenScience/osf.io.git

# adminserver
docker_osf_adminserver: no
docker_osf_adminserver_name: osf_adminserver_1
docker_osf_adminserver_image: centerforopenscience/osf:admin
docker_osf_adminserver_command: "uwsgi --ini /etc/uwsgi/uwsgi.ini"
docker_osf_adminserver_source_conf_file: adminserver/uwsgi.ini
docker_osf_adminserver_conf_dir: /opt/osf_adminserver/conf/
docker_osf_adminserver_conf_file: "{{ docker_osf_adminserver_conf_dir }}uwsgi.ini"
docker_osf_adminserver_data_dir: /opt/osf_adminserver/data/
docker_osf_adminserver_env:
  SOURCE_BRANCH: "{{ docker_osf_source_branch }}"
  SOURCE_REPO: "{{ docker_osf_source_repo }}"
docker_osf_adminserver_net: bridge
docker_osf_adminserver_hostname: "{{ hostname_name }}"
docker_osf_adminserver_expose:
  - 8001
docker_osf_adminserver_ports: []
docker_osf_adminserver_links: []
docker_osf_adminserver_volumes:
  - "{{ docker_osf_adminserver_conf_file }}:/etc/uwsgi/uwsgi.ini"
  - "{{ docker_osf_adminserver_data_dir }}:/data"
docker_osf_adminserver_volumes_from: []

# apiserver
docker_osf_apiserver: no
docker_osf_apiserver_name: osf_apiserver_1
docker_osf_apiserver_image: centerforopenscience/osf:api
docker_osf_apiserver_command: "uwsgi --ini /etc/uwsgi/uwsgi.ini"
docker_osf_apiserver_source_conf_file: apiserver/uwsgi.ini
docker_osf_apiserver_conf_dir: /opt/osf_apiserver/conf/
docker_osf_apiserver_conf_file: "{{ docker_osf_apiserver_conf_dir }}uwsgi.ini"
docker_osf_apiserver_env:
  SOURCE_BRANCH: "{{ docker_osf_source_branch }}"
  SOURCE_REPO: "{{ docker_osf_source_repo }}"
docker_osf_apiserver_net: bridge
docker_osf_apiserver_hostname: "{{ hostname_name }}"
docker_osf_apiserver_expose:
  - 8000
docker_osf_apiserver_ports: []
docker_osf_apiserver_links: []
docker_osf_apiserver_volumes:
  - "{{ docker_osf_apiserver_conf_file }}:/etc/uwsgi/uwsgi.ini"
docker_osf_apiserver_volumes_from: []

# server
docker_osf_server: no
docker_osf_server_name: osf_server_1
docker_osf_server_image: centerforopenscience/osf:web
docker_osf_server_command: "uwsgi --ini /etc/uwsgi/uwsgi.ini"
docker_osf_server_source_conf_file: server/uwsgi.ini
docker_osf_server_conf_dir: /opt/osf_server/conf/
docker_osf_server_conf_file: "{{ docker_osf_server_conf_dir }}uwsgi.ini"
docker_osf_server_env:
  SOURCE_BRANCH: "{{ docker_osf_source_branch }}"
  SOURCE_REPO: "{{ docker_osf_source_repo }}"
docker_osf_server_net: bridge
docker_osf_server_hostname: "{{ hostname_name }}"
docker_osf_server_expose:
  - 5000
docker_osf_server_ports: []
docker_osf_server_links: []
docker_osf_server_volumes:
  - "{{ docker_osf_server_conf_file }}:/etc/uwsgi/uwsgi.ini"
docker_osf_server_volumes_from: []

# celery beat
docker_osf_celery_beat: no
docker_osf_celery_beat_instances: 1
docker_osf_celery_beat_name: osf_celery_beat
docker_osf_celery_beat_image: centerforopenscience/osf:celery
docker_osf_celery_beat_command: "gosu www-data invoke celery_beat --schedule=/celery/celerybeat-schedule"
docker_osf_celery_beat_data_dir: /opt/osf_celery_beat/data/
docker_osf_celery_beat_env:
  SOURCE_BRANCH: "{{ docker_osf_source_branch }}"
  SOURCE_REPO: "{{ docker_osf_source_repo }}"
docker_osf_celery_beat_net: bridge
docker_osf_celery_beat_hostname: "{{ hostname_name }}"
docker_osf_celery_beat_expose: []
docker_osf_celery_beat_ports: []
docker_osf_celery_beat_links: []
docker_osf_celery_beat_volumes:
  - "{{ docker_osf_celery_beat_data_dir }}:/celery"
docker_osf_celery_beat_volumes_from: []

# celery worker
docker_osf_celery_worker: no
docker_osf_celery_worker_instances: 2
docker_osf_celery_worker_name: osf_celery_worker
docker_osf_celery_worker_image: centerforopenscience/osf:celery
docker_osf_celery_worker_command: "gosu www-data invoke celery_worker --hostname=worker{{ item }}.%h"
docker_osf_celery_worker_env:
  SOURCE_BRANCH: "{{ docker_osf_source_branch }}"
  SOURCE_REPO: "{{ docker_osf_source_repo }}"
docker_osf_celery_worker_net: bridge
docker_osf_celery_worker_hostname: "{{ hostname_name }}"
docker_osf_celery_worker_expose: []
docker_osf_celery_worker_ports: []
docker_osf_celery_worker_links: []
docker_osf_celery_worker_volumes:
  - "{{ docker_osf_celery_worker_data_dir }}:/data"
docker_osf_celery_worker_volumes_from: []

# cron
docker_osf_cron: no
docker_osf_cron_instances: 1
docker_osf_cron_name: osf_cron
docker_osf_cron_image: centerforopenscience/osf:celery
docker_osf_cron_command: /bin/bash -c "gosu www-data python -m scripts.cron; touch /var/log/cron.log && rsyslogd && cron && tail -f /var/log/syslog /var/log/cron.log"
docker_osf_cron_env:
  SOURCE_BRANCH: "{{ docker_osf_source_branch }}"
  SOURCE_REPO: "{{ docker_osf_source_repo }}"
docker_osf_cron_net: bridge
docker_osf_cron_hostname: "{{ hostname_name }}"
docker_osf_cron_expose: []
docker_osf_cron_ports: []
docker_osf_cron_links: []
docker_osf_cron_volumes: []
docker_osf_cron_volumes_from: []

# sharejs
docker_osf_sharejs: no
docker_osf_sharejs_name: osf_sharejs_1
docker_osf_sharejs_image: centerforopenscience/osf:sharejs
docker_osf_sharejs_command: "invoke sharejs"
docker_osf_sharejs_env:
  SOURCE_BRANCH: "{{ docker_osf_source_branch }}"
  SOURCE_REPO: "{{ docker_osf_source_repo }}"
  SHAREJS_SERVER_HOST: "{{ docker_osf_sharejs_conf_server_host | default('0.0.0.0') }}"
  SHAREJS_SERVER_PORT: "{{ docker_osf_sharejs_conf_server_port | default('7007') }}"
  SHAREJS_DB_NAME: "{{ docker_osf_sharejs_conf_db_name | default('sharejs') }}"
  SHAREJS_DB_URL: "{{ docker_osf_sharejs_conf_db_url | default('mongodb://localhost:27017/sharejs') }}"
  SHAREJS_CORS_ALLOW_ORIGIN: "{{ docker_osf_sharejs_conf_cors_allow_origin | default('https://test.osf.io') }}"
  SHAREJS_SENTRY_DSN: "{{ docker_osf_sharejs_conf_sentry_dsn | default() }}"
docker_osf_sharejs_net: bridge
docker_osf_sharejs_hostname: "{{ hostname_name }}"
docker_osf_sharejs_expose:
  - 7007
docker_osf_sharejs_ports: []
docker_osf_sharejs_links: []
docker_osf_sharejs_volumes: []
docker_osf_sharejs_volumes_from: []
