# Disables transparent-huge-pages for tokumx

- name: Disables transparent-huge-pages (for tokumx)
  become: yes
  copy:
    src: disable-transparent-hugepages
    dest: /etc/init.d/disable-transparent-hugepages
    mode: 0755
  tags:
    - install


- name: Register the file with init.d
  become: yes
  command: update-rc.d disable-transparent-hugepages defaults
  tags:
    - install


- name: Run service disable transparent hugepages
  become: yes
  shell: service disable-transparent-hugepages start
  tags:
    - install
