- name: Install script csf-docker-wait.conf in upstart
  become: yes
  copy:
    src: csf-docker-wait.conf
    dest: /etc/init/csf-docker-wait.conf
    mode: 0644
  tags:
    - install


- name: Install script csf-docker-started.conf in upstart
  become: yes
  copy:
    src: csf-docker-started.conf
    dest: /etc/init/csf-docker-started.conf
    mode: 0644
  tags:
    - install


- name: Install script csfdocker.sh
  become: yes
  copy:
    src: csfdocker.sh
    dest: /etc/csf/csfdocker.sh
    mode: 0755
  tags:
    - install


- name: Restart CSF & LFD
  become: yes
  command: csf -ra
  tags:
    - install
