

- name: Make sure postgres python driver is installed
  pip: name=

- name: Create a user for gitlab
  postgresql_user: name={{ gitlab_user }}
                   password={{ gitlab_db_pass }}
                   port={{gitlab_db_port}}
                   state=present
  become_user: postgres  # the superuser created after installing postgres
  become: yes


- name: Create the gitlab database
  postgresql_db: name={{ gitlab_db_name }}
                 port={{ gitlab_db_port }}
                 owner={{ gitlab_user }}
                 state=present
  become_user: postgres
  become: yes
