
# http://www.unixmen.com/9-best-practices-to-secure-your-linux-desktop-and-server/

- name: Security Check | Find Form Mail
  shell: find / -name "[Ff]orm[mM]ai*"
  when: check_mailers
  become: yes
  # Failed if any files are found
  register: result
  failed_when: result.stdout
  ignore_errors: yes

# http://www.unixmen.com/9-best-practices-to-secure-your-linux-desktop-and-server/

- name: Security Check | Find CGIeMail
  shell: find / -name "[Cc]giemai*"
  when: check_mailers
  become: yes
  # Fail if any files are found
  register: result
  failed_when: result.stdout
  ignore_errors: yes


- include: tests/deny_port_scans.yml
  when: check_csf

- include: tests/check_configuration.yml


# /etc/motd http://www.unixmen.com/9-best-practices-to-secure-your-linux-desktop-and-server/

# disable telnet http://www.unixmen.com/9-best-practices-to-secure-your-linux-desktop-and-server/
